/**
 * Markdown reporter — Phase 11.3.
 *
 * Produces a GitHub / GitLab PR-comment-compatible Markdown string from an
 * `AuditResult`.  Emoji badges provide at-a-glance severity indicators.
 *
 * Time  O(F)  where F = total findings.
 * Space O(F).
 */

import type { AuditResult, Finding } from '../audit/types.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Emoji badge by severity. */
const SEV_EMOJI: Readonly<Record<string, string>> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
};

/** Emoji badge by grade. */
const GRADE_EMOJI: Readonly<Record<string, string>> = {
  A: '🟢',
  B: '🟢',
  C: '🟡',
  D: '🟠',
  F: '🔴',
};

/** Escape Markdown table cell characters. */
function esc(s: string): string {
  return s
    .replace(/\\/g, '\\\\') // escape backslashes first to avoid double-escaping
    .replace(/\|/g, '\\|')
    .replace(/\n/g, ' ');
}

/** Capitalise first character. */
function cap(s: string): string {
  return s.length === 0 ? s : s[0].toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Render `result` as a Markdown report string.
 *
 * @param result  The audit result to render.
 * @returns       A Markdown string suitable for a PR comment or file.
 */
export function renderMarkdown(result: AuditResult): string {
  const lines: string[] = [];

  const { weighted, grade } = result.overall;
  const gradeEmoji = GRADE_EMOJI[grade] ?? '⚪';

  // ── Header ───────────────────────────────────────────────────────────────
  lines.push('## 🛡️ Zaria Audit Report');
  lines.push('');
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **Project** | \`${result.projectRoot}\` |`);
  lines.push(`| **Date** | ${result.timestamp} |`);
  lines.push(
    `| **Overall Score** | ${gradeEmoji} **${weighted.toFixed(1)} / 100** — Grade **${grade}** |`,
  );
  lines.push('');

  // ── Dimension breakdown ───────────────────────────────────────────────────
  lines.push('### Dimension Breakdown');
  lines.push('');
  lines.push('| Dimension | Score | Weight |');
  lines.push('|---|---|---|');
  for (const entry of result.overall.breakdown) {
    const emoji = entry.score >= 90 ? '🟢' : entry.score >= 70 ? '🟡' : '🔴';
    lines.push(
      `| ${emoji} ${cap(entry.dimension)} | **${entry.score.toFixed(0)}** / 100 | ${(entry.weight * 100).toFixed(0)} % |`,
    );
  }
  lines.push('');

  // ── Finding summary ───────────────────────────────────────────────────────
  const allFindings: Finding[] = result.dimensions.flatMap((d) => d.findings);
  if (allFindings.length === 0) {
    lines.push('### ✅ No Findings');
    lines.push('');
    lines.push('Zero issues detected across all dimensions.');
  } else {
    const counts: Record<string, number> = { critical: 0, high: 0, medium: 0, low: 0 };
    for (const f of allFindings) {
      if (f.severity in counts) counts[f.severity]++;
    }

    lines.push('### Finding Summary');
    lines.push('');
    lines.push(
      `🔴 **Critical:** ${counts.critical} &nbsp; ` +
        `🟠 **High:** ${counts.high} &nbsp; ` +
        `🟡 **Medium:** ${counts.medium} &nbsp; ` +
        `🔵 **Low:** ${counts.low}`,
    );
    lines.push('');

    // Sort by severity, then file path for a stable, predictable table.
    const ORDER: Readonly<Record<string, number>> = { critical: 0, high: 1, medium: 2, low: 3 };
    const sorted = [...allFindings].sort(
      (a, b) => (ORDER[a.severity] ?? 9) - (ORDER[b.severity] ?? 9) || a.file.localeCompare(b.file),
    );

    lines.push('### Findings');
    lines.push('');
    lines.push('| Severity | Rule | File | Message |');
    lines.push('|---|---|---|---|');
    for (const f of sorted) {
      const emoji = SEV_EMOJI[f.severity] ?? '⚪';
      const loc = f.line != null ? `:${f.line}` : '';
      lines.push(
        `| ${emoji} ${cap(f.severity)} | \`${f.ruleId}\` | \`${esc(f.file + loc)}\` | ${esc(f.message)} |`,
      );
    }
  }

  lines.push('');
  lines.push('---');
  lines.push(
    '_Generated by [Zaria](https://github.com/Zoe-life/zaria) — Enterprise Codebase Audit CLI_',
  );

  return lines.join('\n');
}
