import { describe, it, expect } from 'vitest';
import { renderMarkdown } from '../../../src/report/markdown.ts';
import type { AuditResult } from '../../../src/audit/types.ts';

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

const MOCK_RESULT: AuditResult = {
  projectRoot: '/tmp/test-project',
  timestamp: '2026-01-01T00:00:00.000Z',
  dimensions: [
    {
      dimension: 'performance',
      score: 70,
      findings: [
        {
          ruleId: 'PERF001',
          severity: 'high',
          message: 'N+1 query detected',
          file: '/tmp/test-project/src/index.ts',
          line: 20,
          recommendation: 'Use batch queries',
        },
      ],
    },
    { dimension: 'architecture', score: 95, findings: [] },
  ],
  overall: {
    weighted: 82,
    grade: 'B',
    breakdown: [
      { dimension: 'performance', score: 70, weight: 0.25 },
      { dimension: 'architecture', score: 95, weight: 0.25 },
    ],
  },
};

const CLEAN_RESULT: AuditResult = {
  ...MOCK_RESULT,
  dimensions: MOCK_RESULT.dimensions.map((d) => ({ ...d, findings: [] })),
};

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('renderMarkdown', () => {
  it('returns a non-empty string', () => {
    expect(renderMarkdown(MOCK_RESULT).length).toBeGreaterThan(0);
  });

  it('starts with the Zaria header', () => {
    const output = renderMarkdown(MOCK_RESULT);
    expect(output).toContain('## 🛡️ Zaria Audit Report');
  });

  it('contains the project root', () => {
    expect(renderMarkdown(MOCK_RESULT)).toContain('/tmp/test-project');
  });

  it('contains the grade', () => {
    expect(renderMarkdown(MOCK_RESULT)).toContain('Grade **B**');
  });

  it('contains the overall score', () => {
    expect(renderMarkdown(MOCK_RESULT)).toContain('82.0');
  });

  it('contains dimension breakdown table', () => {
    const output = renderMarkdown(MOCK_RESULT);
    expect(output).toContain('### Dimension Breakdown');
    expect(output).toContain('Performance');
  });

  it('contains findings table when there are findings', () => {
    const output = renderMarkdown(MOCK_RESULT);
    expect(output).toContain('### Findings');
    expect(output).toContain('PERF001');
    expect(output).toContain('N+1 query detected');
  });

  it('shows no-findings message on clean result', () => {
    const output = renderMarkdown(CLEAN_RESULT);
    expect(output).toContain('✅ No Findings');
    expect(output).not.toContain('### Findings');
  });

  it('ends with generated-by footer', () => {
    const output = renderMarkdown(MOCK_RESULT);
    expect(output).toContain('Generated by');
    expect(output).toContain('Zaria');
  });

  it('escapes pipe characters in file paths', () => {
    const result: AuditResult = {
      ...MOCK_RESULT,
      dimensions: [
        {
          dimension: 'performance',
          score: 70,
          findings: [
            {
              ruleId: 'PERF001',
              severity: 'high',
              message: 'msg|with|pipes',
              file: '/path/file.ts',
              recommendation: 'rec',
            },
          ],
        },
      ],
    };
    const output = renderMarkdown(result);
    expect(output).toContain('\\|with\\|');
  });

  it('escapes backslash characters to prevent double-escaping', () => {
    const result: AuditResult = {
      ...MOCK_RESULT,
      dimensions: [
        {
          dimension: 'performance',
          score: 70,
          findings: [
            {
              ruleId: 'PERF001',
              severity: 'high',
              message: 'path\\with\\backslashes',
              file: '/path/file.ts',
              recommendation: 'rec',
            },
          ],
        },
      ],
    };
    const output = renderMarkdown(result);
    expect(output).toContain('\\\\with\\\\');
  });
});
